server:
  port: 8000

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/nota?serverTimezone=UTC
    username: root
    password: root
    pool-size: 30
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate:
          format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

